// <auto-generated />
using System;
using FadeAfro.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FadeAfro.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260503084259_DescriptionRemovedFromMasterProfile")]
    partial class DescriptionRemovedFromMasterProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FadeAfro.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MasterProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("MasterProfileId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.AppointmentService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("AppointmentId", "ServiceId")
                        .IsUnique();

                    b.ToTable("AppointmentServices", (string)null);
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.MasterProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("MasterId")
                        .IsUnique();

                    b.ToTable("MasterProfiles", (string)null);
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.MasterSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("MasterProfileId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MasterProfileId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("MasterSchedules", (string)null);
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.MasterUnavailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("MasterProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MasterProfileId", "Date")
                        .IsUnique();

                    b.ToTable("MasterUnavailabilities", (string)null);
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<Guid>("MasterProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasterProfileId");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("FadeAfro.Domain.Entities.User", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FadeAfro.Domain.Entities.MasterProfile", "MasterProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("MasterProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("MasterProfile");
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.AppointmentService", b =>
                {
                    b.HasOne("FadeAfro.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Services")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FadeAfro.Domain.Entities.Service", "Service")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Appointment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.MasterProfile", b =>
                {
                    b.HasOne("FadeAfro.Domain.Entities.User", "Master")
                        .WithOne()
                        .HasForeignKey("FadeAfro.Domain.Entities.MasterProfile", "MasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.MasterSchedule", b =>
                {
                    b.HasOne("FadeAfro.Domain.Entities.MasterProfile", "MasterProfile")
                        .WithMany("Schedules")
                        .HasForeignKey("MasterProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterProfile");
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.MasterUnavailability", b =>
                {
                    b.HasOne("FadeAfro.Domain.Entities.MasterProfile", "MasterProfile")
                        .WithMany("Unavailabilities")
                        .HasForeignKey("MasterProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterProfile");
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.Notification", b =>
                {
                    b.HasOne("FadeAfro.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.Service", b =>
                {
                    b.HasOne("FadeAfro.Domain.Entities.MasterProfile", "MasterProfile")
                        .WithMany("Services")
                        .HasForeignKey("MasterProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterProfile");
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.MasterProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Schedules");

                    b.Navigation("Services");

                    b.Navigation("Unavailabilities");
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.Service", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("FadeAfro.Domain.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
