using FadeAfro.Application.Features.MasterUnavailabilities.Common;

namespace FadeAfro.Application.Features.MasterUnavailabilities.GetMasterUnavailabilities;

public record GetMasterUnavailabilitiesResponse(List<UnavailabilityDto> Unavailabilities);
